	\context ChordNames
		\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% intro
		\mark \default
		\skip 1*10

		% estrofa 1
		\mark \default
		\skip 1*8

		% estrofa 2
		\mark \default
		\skip 1*8

		% puente 1
		\mark \default
		\skip 1*8

		% coro 1
		\mark \default
		\skip 1*7

		% interludio
		\mark \default
		\skip 1*8

		% estrofa 3
		\mark \default
		\skip 1*8

		% estrofa 4
		\mark \default
		\skip 1*8

		% puente 2
		\mark \default
		\skip 1*8

		% coro 2
		\mark \default
		\skip 1*9

		% coro 3
		\mark \default
		\skip 1*7

		% finale
		\mark \default
		}
