	\context ChordNames
		\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% intro
		\mark \default

		% estrofa 1
		\mark \default

		% estrofa 2
		\mark \default

		% puente 1
		\mark \default

		% coro 1
		\mark \default

		% interludio
		\mark \default

		% estrofa 3
		\mark \default

		% estrofa 4
		\mark \default

		% puente 2
		\mark \default

		% coro 2
		\mark \default

		% coro 3
		\mark \default

		% finale
		\mark \default
		}
